Repository Okapi-Oriented-Programming/2025-OOPL, pull requests merged in 2025-03, with the labels that each got.

#13 <SCP Roguelike> Proposal
  Proposal/112590052/Proposal.md
  Proposal/112590052/image.png
Labels: Ready to Merge

#16 <Helltaker> Proposal
  Proposal/111590051/Giraffe_Adventure.png
  Proposal/111590051/Proposal.md
Labels: Ready to Merge, 加選

#23 <イニシエダンジョン> Proposal
  Proposal/112590003-112590056/Proposal.md
  Proposal/112590003-112590056/lab1.png
Labels: Ready to Merge

#24 <超級瑪莉歐> Proposal
  Proposal/112590013-112590019/Proposal.md
  giraffe_adventure.png
Labels: Ready to Merge

#30 <Jetpack Joyride> Proposal
  .idea/.gitignore
  .idea/2025-OOPL.iml
  .idea/editor.xml
  .idea/modules.xml
  .idea/vcs.xml
  Proposal/111590007-111590062/111590062_giraffe.png
  Proposal/111590007-111590062/Proposal.md
  Proposal/111590007-111590062/S__4055055.jpg
  Proposal/111590007-111590062/giraffe.png
  Proposal/111590007-111590062/image.png
  Proposal/111590007-111590062/oop.png
Labels: Ready to Merge, 加選

#35 <Bloons Tower Defense 3> Proposal
  Proposal/112590034/Proposal.md
Labels: Ready to Merge

#37 <雪人兄弟丐版復刻> Proposal
  LAB0/Pass Girafee Adventure.png
  Proposal/112590021-112590055/Proposal.md
Labels: Ready to Merge

#43 <元氣騎士> Proposal
  Proposal/112590035-112590042/Proposal.md
  Proposal/112590035-112590042/soul_knight.jpeg
Labels: Ready to Merge

#52 <倉庫番>Proposal(推箱子)
  Proposal/110590041-110590062/OOP成績證明_110590041.jpg
  Proposal/110590041-110590062/OOP成績證明_110590062.jpg
  Proposal/110590041-110590062/Proposal.md
  Proposal/110590041-110590062/長頸鹿作業截圖_1.png
  Proposal/110590041-110590062/長頸鹿作業截圖_2.png
  Proposal/112820018/OOP成績證明.jpg
  Proposal/112820018/Proposal.md
  Proposal/112820018/長頸鹿作業截圖.jpg
Labels: Ready to Merge, 加選

#21 <I Wanna Be The Boshy> Proposal
  Proposal/112590011-112590044/Proposal.md
Labels: Ready to Review

#29 <超級瑪莉歐> Proposal
  Proposal/112590017-112590050/Proposal.md
Labels: Ready to Review

#25 <星之卡比> Proposal
  .DS_Store
  Proposal/.DS_Store
  Proposal/112590048-112590049/Proposal.md
Labels: Ready to Review

#56 <植物大戰殭屍> Proposal
  Proposal/112590060-112590051/Proposal.md
Labels: Ready to Review

#60 <Helltaker> proposal
  Proposal/110820037-112590032/Giraffe Adventure.png
  Proposal/110820037-112590032/Proposal.md
Labels: Ready to Review

#61 <VVVVVV demo> Proposal
  Proposal/111332012/111332012_OOP grade.jpg
  Proposal/111332012/Proposal.md
  Proposal/111332012/lab fin.png
  Proposal/111332012/lab fin2.png
Labels: Ready to Merge, 加選

#63 <植物大戰殭屍> Proposal
  Proposal/109590054-109590056/109590054.png
  Proposal/109590054-109590056/109590056.jpg
  Proposal/109590054-109590056/Proposal.md
  Proposal/109590054-109590056/螢幕擷取畫面 2025-02-28 024544.png
  Proposal/111820024-111820030/Proposal.md
Labels: Ready to Merge, 加選

#65 <Legacy of Defense - Prologue> Proposal
  Proposal/110590052/Grade.png
  Proposal/110590052/Proposal.md
  Proposal/110590052/image.png
Labels: 加選

#55 <超級瑪利歐> Proposal
  .DS_Store
  Proposal/.DS_Store
  Proposal/112590045-112590047/.DS_Store
  Proposal/112590045-112590047/Proposal.md
Labels: Ready to Review

#62 <Bloons Tower Defense 2> Proposal
  Proposal/112590023-112590028/Proposal.md
  Proposal/112590023-112590028/image.png
Labels: Ready to Review

#8 <推箱子> Proposal
  Proposal/110590451-110590452/proposal.md
  加選/110590451.jpg
  加選/110590452.jpg
  加選/練習完成.png
Labels: Ready to Review, 加選

#11 <植物大戰僵屍>Proposal
  Proposal/110590453-110590454/110590453.png
  Proposal/110590453-110590454/110590454.jpg
  Proposal/110590453-110590454/Proposal.md
Labels: Ready to Review, 加選

#26 <Celeste Pico-8> Proposal
  Proposal/112590452-112590453/PTSD-Practice-Giraffe-Adventure_Finished.png
  Proposal/112590452-112590453/Proposal.md
Labels: Ready to Review

#38 <Pico Park>Proposal
  Proposal/111820010-111820019/Proposal.md
Labels: Ready to Review
